### ISSUE TITLE
Noto Sans Arabic Arabic decimal and thousands separators

### ISSUE THREAD

**Issue by behdad** [notofonts/arabic#11]
Make sure these have the correct form (the form used in Persian), for all languages. Right now the Noto Naskh Arabic only has them for Persian, and the defaults (Arabic) are like comma and inverted comma. I suggest changing them all to be the shape for Persian.

**Comment by simoncozens** [comment]
I erroneously closed #7 based on my reading of L2/00-151, because I didn't know about the Persian localization. This is the same issue anyway.

**Comment by NightFurySL2001** [comment]
I would like to ask if it is normal for the Noto Sans Arabic to have different comma shape between Arabic semicolon <؛> (U+061B) and Arabic comma <،> (U+060C). In Noto Sans Arabic, the standard Latin comma <,> and Arabic semicolon uses the Noto Sans wedge shape, but the other comma-like punctuations use the tadpole shape. Unicode for below from left to right are:
066B, 066C, 002C, 2E41, 204F, 060C, 061B
![image](https://user-images.githubusercontent.com/33471049/229276584-ac839620-f6c3-4833-a908-991f2f7a9e3e.png)

In Noto Kufi Arabic, all the comma-like shapes use the Noto Sans wedge shape.
066B, 066C, 060C, 061B
![image](https://user-images.githubusercontent.com/33471049/229276740-28f8c192-d3f3-4496-800f-67950e533cd1.png)
