### ISSUE TITLE
Bad 'dlig' ligature of Arabic cube root and fourth root

### ISSUE THREAD

**Issue by dscorbett** [notofonts/arabic#13]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
'dlig' composes U+0606 and U+0607 into a single glyph.

### Character data
؆؇
U+0606 ARABIC-INDIC CUBE ROOT
U+0607 ARABIC-INDIC FOURTH ROOT

### Screenshot
Default:
![؆؇](https://user-images.githubusercontent.com/1124347/40493917-a311997c-5f41-11e8-93a7-e7c1ca2604f0.png)
With 'dlig':
![؆؇](https://user-images.githubusercontent.com/1124347/40493472-cde19a5e-5f40-11e8-917f-6ddf67cc98e7.png)

**Comment by simoncozens** [comment]
But apparently fixed again in 2.010! I've added a regression test.
