### ISSUE TITLE
List of all Arabic codepoints missing from NotoSansArabic and NotoSansArabicUI 2.002

### ISSUE THREAD

**Issue by nizarsq** [notofonts/arabic#18]
Below is a list of all Arabic codepoints missing from NotoSansArabic and  NotoSansArabicUI Version 2.002:

U+2013 U+2014 U+2018 U+2019 U+201c U+201d U+2039 U+203a U+2212 U+0028 U+0029 U+002b U+002f U+003d U+005b U+005c U+005d U+007b U+007c U+007d U+00b7 U+00d7 U+00f7 U+feff

**Comment by simoncozens** [comment]
I'm going to close this, not because we've filled the gaps, but because we now maintain automatically generated and updated gap lists [here](https://notofonts.github.io/overview/)
