### ISSUE TITLE
Problems with glyphs ؁ (U+0601), ؀ (U+0600), and others۔

### ISSUE THREAD

**Issue by IlyasTarpan** [notofonts/arabic#182]
Greetings. Noto Naskh Arabic has problems with several sub-digit glyphs: ؁ (U+0601), ؀ (U+0600), ؂ (U+0603), ؃ (U+0602).
The video shows (it is Word) how it should work (the top two fonts are Amiri and Arabic typesetting). But in Noto Naskh Arabic it doesn't work well, the glyphs overlap each other. (I downloaded this version of the font from the Google Fonts website.)

https://user-images.githubusercontent.com/113206717/204013150-721af563-ff28-4d66-a306-6b0c461fcfc4.mp4

And one more thing: I don’t know whether to contact you (I think you should contact the Samsung service), but in android, there are also problems with these glyphs.
The video (it is a Samsung notes, anв similar situation everywhere -in messengers, video and photo editors, etc.) below shows that in order for the numbers to be displayed on the glyph on top, you first need to write the numbers themselves (١٢٣٤), and then the sub-digit glyph. This is wrong - first you need to write a subdigit sign. And one more problem - even if you do this, the numbers will be in reverse order (it should be, ؁١٢٣٤  but it looks like ؁٤٣٢١).

https://user-images.githubusercontent.com/113206717/204015070-942edc4d-1f3f-451d-b219-08d19a21afe1.mp4

Sorry for my English, I'm writing through a translator.

**Comment by simoncozens** [comment]
Thanks for the issue report! I think this is the same as #6.

**Comment by simoncozens** [comment]
(Closing, let's go to #6)
