### ISSUE TITLE
Naskh re-engineering review

### ISSUE THREAD

**Issue by simoncozens** [notofonts/arabic#185]
I've been working on a re-engineering of the Naskh font, with several aims:

* maintainable code, glyph naming, structure, etc.
* fix outstanding issues
* improve minority language support
* use decomposition to reduce glyphset while...
* ...increasing Unicode coverage!
* be an exemplar for glyph naming / engineering of the other Noto Arabic fonts.

I think it's kind of done, and I'm happy with it, but given the importance of this font, I'm not going to deploy it until people have had a chance to look at it and make sure it does what it's supposed to.

If you want to try builds of the Naskh beta, it's [here](https://github.com/notofonts/arabic/actions/runs/4051965270).

I've used [diffenator2](https://github.com/googlefonts/diffenator2) to QA it and there are a number of changes, some of which are deliberate improvements and others might be improvements but I'm not sure. In particular, I am not sure about small-v size and positioning, heights of things like shaddas and their positioning on lams, kafs, etc. Here are the diff results for the standard Arabic wordlist:

Before:
<img width="932" alt="Screenshot 2023-01-31 at 08 36 02" src="https://user-images.githubusercontent.com/106728/215709548-7102f461-77a4-4735-ad14-9fd4ea6d93c7.png">
After:
<img width="930" alt="Screenshot 2023-01-31 at 08 36 20" src="https://user-images.githubusercontent.com/106728/215709619-e34fd11e-fec6-4b10-99cf-74404baf15f8.png">

(Some changes are very small mark shifts.)

As animation:
![arabic](https://user-images.githubusercontent.com/106728/215717433-3fdedb1d-e849-4640-9e10-98bf0ee039f1.gif)

And I put together an extended Arabic wordlist for the diffenator as well. These are mostly inverted-v fixes but there are a few other things in there too:

Before:
<img width="1166" alt="Screenshot 2023-01-31 at 08 38 50" src="https://user-images.githubusercontent.com/106728/215710145-dea2aa39-de4d-47e0-a77e-c86668d08597.png">
<img width="1157" alt="Screenshot 2023-01-31 at 08 39 11" src="https://user-images.githubusercontent.com/106728/215710227-6363b8dc-6841-4baa-b057-f567126b8629.png">

After:

<img width="1170" alt="Screenshot 2023-01-31 at 08 39 50" src="https://user-images.githubusercontent.com/106728/215710389-9302a702-a772-4662-bd2d-f011fa3f725c.png">
<img width="1155" alt="Screenshot 2023-01-31 at 08 39 33" src="https://user-images.githubusercontent.com/106728/215710315-58f82fbe-142d-4c50-aa3b-86e3667ba9b1.png">

As animation:
![arabic2](https://user-images.githubusercontent.com/106728/215717795-3c7844e9-4f72-40a7-a432-0a477949b331.gif)

If anyone has the opportunity to feedback some comments I would be very grateful!

**Comment by yanone** [comment]
First impression of the new version is very good. I also place the tashkeel centered on the final/isolated lam.
The mark positioning is very inconsistent vertically, both the distance to the base letters as well as distance between marks. This may not be something that you can easily resolve. Personally I have a ufo2ft filter for this that ensures that the final top anchors are at a certain absolute minimum height, and I would love to add a minimum distance from the top bbox border as well, haven't done it yet.

What strikes me about both old and new is inconsistencies with the fatha-tanween and kasra-tanween. First, the kasra-tan is denser in design than the fatha-tan, which is odd. I feel like all of them can do with a tiny bit more space, even within tashkeel ligatures, which seem to be separate outlines, not components. Even at this size they're just a visual blob, let alone at normal reading size. Then, the font could benefit from a decomposition rule for double fathas (and maybe kasras), see `تقريباََ`, third row. Those are clearly two stacked fathas that want to become a fatha-tan.

The anchors on the lam in the lower examples are not centered as in the above. And the various accents and tashkeel on final/isolated yeh/alefmaksura are all over the place, but I can't say where they each best belong. Only that they are inconsistent.

**Comment by simoncozens** [comment]
Thanks for taking a look!

> The mark positioning is very inconsistent vertically, both the distance to the base letters as well as distance between marks. This may not be something that you can easily resolve.

Well, I can, but I was trying *not* to adjust mark positioning too much because I didn't want to deviate from the original; I don't feel comfortable making those decisions. If others also think it would improve the font, maybe we could look at doing that too.

> What strikes me about both old and new is inconsistencies with the fatha-tanween and kasra-tanween. First, the kasra-tan is denser in design than the fatha-tan, which is odd. 

Good spot! And these were not components, either, but designed glyphs. Maybe there was a deliberate choice, but maybe it was an oversight. Who can fathom the ways of Monotype?

> Those are clearly two stacked fathas that want to become a fatha-tan.

Hrm. I haven't seen another font which does this! I tend to think we should give the user what they ask for; if they want a fathatan they should ask for one.

> The anchors on the lam in the lower examples are not centered as in the above.

Thank you - for some odd reason I thought final lam shouldn't have centered accents, but of course it should.

> And the various accents and tashkeel on final/isolated yeh/alefmaksura are all over the place, but I can't say where they each best belong.

I shall take a look at this.

**Comment by simoncozens** [comment]
@LornaSIL @khaledhosny Please take a look if you have the chance. Thanks!

**Comment by LornaSIL** [comment]
Generally, I think it looks good too.

I'm noticing a difference between the combining marks on final lam and final feh-like characters. The above anchor is moved over to the left. This is often done by designers because it makes the overall height a bit smaller if the combining marks aren't quite so tall and if it's over the bowl it could be considered nicer. That may be a regional preference as well.

The other one that isn't different, but "old" and "new" have a strange above position when hamza+fatha are used on final yeh-forms. In the first example shadda+fatha look fine, so maybe the hamza+fatha ligature doesn't have an attachment point?
![image](https://user-images.githubusercontent.com/7071907/215820690-cd0c0465-2b9a-44db-9c90-3047b1875468.png)

**Comment by simoncozens** [comment]
Okay, I've fixed the final alef maksura/yehHamza positioning issue, and I'm going to release this.

**Comment by simoncozens** [comment]
Apparently SMALL TAH BELOW got removed, I should fix that.
