### ISSUE TITLE
Kufi re-engineering review

### ISSUE THREAD

**Issue by simoncozens** [notofonts/arabic#186]
In a similar vein to the [re-engineer of Noto Naskh Arabic](https://github.com/notofonts/arabic/issues/185), I have re-worked Noto Kufi Arabic. (Sans, you're next.) Same goals:

* maintainable code, glyph naming, structure, etc.
* fix outstanding issues
* improve minority language support
* use decomposition to reduce glyphset while...
* ...increasing Unicode coverage!
* consistent glyph naming / engineering with other Noto Arabic fonts.

This time there are fairly few visible changes, but the font is 50% smaller. Here are the diffs. Isolates:

![isolates](https://user-images.githubusercontent.com/106728/230359005-f0ae102b-4894-4366-a0b0-a4cf7526dd30.gif)

Standard Arabic:

![std-arabic](https://user-images.githubusercontent.com/106728/230359046-a1272927-cec2-441f-9201-7c5f266a2aaf.gif)

Extended Arabic:

![ext-arabic](https://user-images.githubusercontent.com/106728/230359099-fba19378-bf61-43c4-b3c4-ebc64f3b30c2.gif)

Again I think this is an improvement but there may be stuff I have missed. Builds are available [here](https://github.com/notofonts/arabic/actions/runs/4628425866).

@khaledhosny @yanone @lornasil and any others, if you have a moment to look over these I would appreciate it.

**Comment by khaledhosny** [comment]
Looks good, re- ڵ, when I checked with Kurdish readers, I was told the mark should be positioned above the stem (like the old positioning you have here).

**Comment by yanone** [comment]
What's with the three dots of the lam in the second image, 3rd row from bottom, left-most? Never seen that.

**Comment by yanone** [comment]
The ري dot positioning collision in بريقه is a regression.

**Comment by simoncozens** [comment]
> Looks good, re- ڵ, when I checked with Kurdish readers, I was told the mark should be positioned above the stem (like the old positioning you have here).

Thank you - will fix!

**Comment by simoncozens** [comment]
It was  ݠَاࢩٛ, and Khaled has now fixed it:
![shape](https://github.com/notofonts/arabic/assets/106728/9cfe6dcb-f1e5-4af4-8d48-9632ab75f472)
