### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by m4rc1e** [notofonts/arabic#187]
I'm reviewing the diff reports generated in https://github.com/notofonts/arabic/actions/runs/4788911633

## Noto Naskh:

**Modified Glyphs:**

before: 

<img width="188" alt="Screenshot 2023-04-27 at 17 16 51" src="https://user-images.githubusercontent.com/7525512/234926120-d2098c48-caff-4129-91e9-bb9089915007.png">

after:

<img width="158" alt="Screenshot 2023-04-27 at 17 17 08" src="https://user-images.githubusercontent.com/7525512/234926187-f027bea6-5b80-416a-abfb-eb3ea7d5c892.png">

Old form matches OS X default better

**Missing glyphs:**

<img width="607" alt="Screenshot 2023-04-27 at 17 18 16" src="https://user-images.githubusercontent.com/7525512/234926436-d51ed3e1-066f-4e4c-8374-df278aeb9b5e.png">

**Mark positions which seem suspect**

Before:

<img width="67" alt="Screenshot 2023-04-27 at 17 19 35" src="https://user-images.githubusercontent.com/7525512/234926702-c3172bf3-2b57-435d-bf49-c39053599de4.png">

After:

<img width="70" alt="Screenshot 2023-04-27 at 17 19 06" src="https://user-images.githubusercontent.com/7525512/234926592-94bfdf85-e65a-4460-91fd-3cb722bd5dd5.png">

Otherwise LGTM. I'll look at the other as well.

**Comment by simoncozens** [comment]
The "filled damma" change in letter ۇ is deliberate; see #25.

**Comment by m4rc1e** [comment]
## Noto Naskh Arabic UI

The hamza high now appear too big (I could be wrong)

before:

<img width="373" alt="Screenshot 2023-04-27 at 17 26 14" src="https://user-images.githubusercontent.com/7525512/234928162-cc4a6eef-0046-4795-bd67-b9357041366a.png">

after:

<img width="370" alt="Screenshot 2023-04-27 at 17 26 32" src="https://user-images.githubusercontent.com/7525512/234928247-08e21c2c-dc1c-4385-9574-965764dccc4c.png">

otherwise LGTM

**Comment by m4rc1e** [comment]
## Noto Sans Arabic

jeem dot looked better before

before:

<img width="109" alt="Screenshot 2023-04-27 at 17 30 44" src="https://user-images.githubusercontent.com/7525512/234929280-7de97856-1621-40f4-ae1e-8fcc82e8c38c.png">

after:

<img width="111" alt="Screenshot 2023-04-27 at 17 31 20" src="https://user-images.githubusercontent.com/7525512/234929412-dc2cc631-2087-4e9b-97fa-80ac5660e824.png">

Looks like there may be contour direction issues for بھٲئی

before:

<img width="78" alt="Screenshot 2023-04-27 at 17 34 35" src="https://user-images.githubusercontent.com/7525512/234930163-e8ed3b87-0cfe-48f9-a625-d55271c0c5aa.png">

after:

<img width="72" alt="Screenshot 2023-04-27 at 17 34 51" src="https://user-images.githubusercontent.com/7525512/234930229-8516e33a-3e82-4a96-a623-e9eecc6ce186.png">

otherwise LGTM

**Comment by khaledhosny** [comment]
> ## Noto Naskh Arabic UI
> 
> The hamza high now appear too big (I could be wrong), when compared to other system fonts.
> 
> before:
> 
> <img alt="Screenshot 2023-04-27 at 17 26 14" width="373" src="https://user-images.githubusercontent.com/7525512/234928162-cc4a6eef-0046-4795-bd67-b9357041366a.png">
> 
> after:
> 
> <img alt="Screenshot 2023-04-27 at 17 26 32" width="370" src="https://user-images.githubusercontent.com/7525512/234928247-08e21c2c-dc1c-4385-9574-965764dccc4c.png">
> 
> otherwise LGTM

This is deliberate as well (in master they also gets the filled comma form), see #39.

**Comment by khaledhosny** [comment]
> ## Noto Sans Arabic
> 
> jeem dot looked better before
> 
> before:
> 
> <img alt="Screenshot 2023-04-27 at 17 30 44" width="109" src="https://user-images.githubusercontent.com/7525512/234929280-7de97856-1621-40f4-ae1e-8fcc82e8c38c.png">
> 
> after:
> 
> <img alt="Screenshot 2023-04-27 at 17 31 20" width="111" src="https://user-images.githubusercontent.com/7525512/234929412-dc2cc631-2087-4e9b-97fa-80ac5660e824.png">
> 
> Looks like there may be contour direction issues for بھٲئی
> 
> before:
> 
> <img alt="Screenshot 2023-04-27 at 17 34 35" width="78" src="https://user-images.githubusercontent.com/7525512/234930163-e8ed3b87-0cfe-48f9-a625-d55271c0c5aa.png">
> 
> after:
> 
> <img alt="Screenshot 2023-04-27 at 17 34 51" width="72" src="https://user-images.githubusercontent.com/7525512/234930229-8516e33a-3e82-4a96-a623-e9eecc6ce186.png">
> 
> otherwise LGTM

Both issues are fixed now.
