### ISSUE TITLE
Wrong display of Uyghur letter ھ ?

### ISSUE THREAD

**Issue by sal-ammoniac** [notofonts/arabic#189]
### Font 
  NotoNaskhArabic-Regular.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic
  >   Date: 2023-04-20

### Font Version
  Version 2.016

### OS name and version
  Windows 11 Version 22H2

### Application name and version
  Microsoft Edge Stable Version 113

### Issue
  The letter "ھ" in Uyghur will only show its isolated form even in medial and final form.
 however,it should be showing "ـھـ" in its medial and final form.

**Comment by sal-ammoniac** [comment]
the letter is U+06BE ھ ARABIC LETTER HEH DOACHASHMEE

**Comment by simoncozens** [comment]
This appears to be by design, but I don't know if it's correct. The font does contain (and correctly display) medial, initial and final forms for heh doachashmee, but they are very similar to the isolated form (initial and medial forms do not have a raised "tail" at the exit stroke).

I'm not sure why the "figure eight" forms are not used in the medial/final.

**Comment by moyogo** [comment]
Unicode 14.0 and 15.0 updated the ["Letter heh" paragraph](https://www.unicode.org/versions/Unicode15.0.0/ch09.pdf#page=27) with the following info and table relevant to 06BE:

> U+06BE ARABIC LETTER HEH DOACHASHMEE is used to represent any heh-like letter that appears with left stems in all contextual forms. All four forms should have two horizontal or vertical “eyes.” The exact contextual shapes of the letter depend on the language and the style of writing. Four variations for knotted heh are shown in Table 9-9.

<img width="1008" alt="Screenshot 2023-05-21 at 14 16 07" src="https://github.com/notofonts/arabic/assets/1923747/29d85a41-75dd-4a22-8aaa-98f8de30b1c3">

**Comment by simoncozens** [comment]
So we do have the medial form of heh which we could use here for medial hehDoachashmee, but obviously no final form. And the medial heh connection looks kind of weird on the left, but again maybe that's by design:
![shape](https://github.com/notofonts/arabic/assets/106728/33cabf9c-8596-4c4d-bc2d-c0294adefe1d)

**Comment by sal-ammoniac** [comment]
> So we do have the medial form of heh which we could use here for medial hehDoachashmee, but obviously no final form. And the medial heh connection looks kind of weird on the left, but again maybe that's by design: ![shape](https://user-images.githubusercontent.com/106728/239843042-33cabf9c-8596-4c4d-bc2d-c0294adefe1d.png)

But this will cause ambiguity between Uyghur "e" and "h".

**Comment by sal-ammoniac** [comment]
Many Turkic languages of Central Asia like Uyghur as well as Kurdish use the modification of the letter for front vowels [æ] or [ɛ]. This has its own code point (U+06D5). To distinguish it from Arabic hāʾ /h/ the letter lacks its initial and medial forms:

**Comment by moyogo** [comment]
@sal-ammoniac Simon suggested using the medial form of U+0647 for the medial and final forms of U+06BE, and possibly adjusting the end stroke of the final form:
<img width="471" alt="Screenshot 2023-05-24 at 10 13 11" src="https://github.com/notofonts/arabic/assets/1923747/d909e445-5e1e-489f-9f69-3f3f77cd12f1">

**Comment by r12a** [comment]
Hmm. If it will look like Myogo's example, it seems a bit clunky to me.  Compare it with Scheherazade, where the final form has modulation similar to the isolate form.


<img width="477" alt="Screenshot 2023-05-24 at 12 21 56" src="https://github.com/notofonts/arabic/assets/4839211/a4146f36-5f7b-464a-9728-30e1b1a251da">

**Comment by moyogo** [comment]
That’s how the letter is drawn though:
<img width="422" alt="Screenshot 2023-05-24 at 14 24 04" src="https://github.com/notofonts/arabic/assets/1923747/1194da3c-cd30-43d4-8b70-e87faa04742b">

**Comment by sal-ammoniac** [comment]
that seems ok @moyogo
