### ISSUE TITLE
Noto Kufi Arabic does not contain the period, colon, exclamation mark glyphs so it renders the end my paragraph with empty boxes

### ISSUE THREAD

**Issue by Lilly1988** [notofonts/arabic#191]
**Title** 
Noto Kufi Arabic does not contain the period, colon, exclamation mark glyphs so it renders the end my paragraph with empty boxes

**Font** 
Full file name, 'NotoKufiArabic-Thin.ttf'.
Full file name, 'NotoKufiArabic-Thin.ttf'.
Full file name, 'NotoKufiArabic-ExtraLight.ttf'.
Full file name, 'NotoKufiArabic-Light.ttf'.
Full file name, 'NotoKufiArabic-Regular.ttf'.
Full file name, 'NotoKufiArabic-Medium.ttf'.
Full file name, 'NotoKufiArabic-Bold.ttf'.
Full file name, 'NotoKufiArabic-ExtraBold.ttf'.
Full file name, 'NotoKufiArabic-ExtraBold.ttf'.
Full file name, 'NotoKufiArabic-Black.ttf'.

**Where the font came from, and when**
  >   Site: https://fonts.google.com/noto/specimen/Noto+Kufi+Arabic
  >   Date: 2023-05-22

** Issue**
 Noto Kufi Arabic does not contain the period, colon, exclamation mark glyphs so it renders the end my paragraph with empty boxes
<img width="650" alt="Screen Shot 2023-05-22 at 5 02 51 PM" src="https://github.com/notofonts/noto-cjk/assets/134228799/ffab1b40-93db-4ddb-843d-28d9e291f8d3">

**Comment by simoncozens** [comment]
This will be fixed when the new version of Noto Kufi Arabic is onboarded to Google Fonts (I'm making the request now). That will take a few weeks to go through the onboarding process, though. If you want a working version in the meantime, you can get the "full" version from the Kufi release [here](https://github.com/notofonts/arabic/releases).
