### ISSUE TITLE
Noto Naskh Arabic لله character sequence including possible diacritic combinations does not ligate

### ISSUE THREAD

**Issue by WanAhmadShahmi98** [notofonts/arabic#192]
### Font 
  * NotoNaskhArabic-Bold.otf
  * NotoNaskhArabic-Medium.otf
  * NotoNaskhArabic-Regular.otf
  * NotoNaskhArabic-SemiBold.otf

### Where the font came from, and when
* Site: https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoNaskhArabic/full/otf
* Date: 2023-05-25

### Font Version
  * v2.016

### Issue
The character sequence of
  1. U+0644 ARABIC LETTER LAM ⟨ل⟩
  2. U+0644 ARABIC LETTER LAM ⟨ل⟩
  3. U+0647 ARABIC LETTER HEH ⟨ه⟩

in this version on Noto Naskh Arabic seems to not ligate into the popular ligature as most fonts do. This also occurs when the Lam+Lam+Heh combined with some Arabic diacritic combinations, especially for the second Lam. In older version of Noto Naskh Arabic used in some Android devices (which I do not know the stock font version), the second Lam appears shorter than the first Lam and appears likewise when combined with diacritic combinations on that second Lam.

![Screenshot_2023-05-22-22-15-58-108-edit_com android chrome](https://github.com/notofonts/arabic/assets/42583480/b91a9414-e468-4a99-a0fd-41c57f87f686)
The font as demostrated in Google​ Fonts, with the second Lam combined with two diacritics in sequence: U+0651 ARABIC SHADDA, U+0670 ARABIC LETTER SUPERSCRIPT ALEF.

![Screenshot_2023-05-17-23-06-24-232-edit_com android chrome](https://github.com/notofonts/arabic/assets/42583480/35bf7b87-ec3c-41b6-a6e2-8bb702f3f1e5)
The Lam-Lam-Heh tested with and without diacritics, and with and without prefix letter, in this image, U+0671 ARABIC LETTER ALEF WASLA and U+0627 ARABIC LETTER ALEF was used before the Lam-Lam-Heh combination. Tags: Allah, Lillah.
> (Also shown in the font test U+0675 ARABIC LETTER HIGH HAMZA ALEF when prejoined with U+0644 ARABIC LETTER LAM with diacritics on both letters to form the Quranic word _li-Ādama_, which I think the above-letter diacritics' height is quite far and small, but this can be a separate issue and possibly related to issue #8 and may not a matter of concern).

**Comment by khaledhosny** [comment]
The sequence that automatically ligates is exactly اللّٰه, any other variation does not. There is also a dlig feature that will force any لله to ligate, but Google Fonts might be stripping such features from fonts they serve.

As for U+0675, that is a deprecated code point and its use for li-Ādama is a hack, the correct sequence is لـٔا, see #26.
