### ISSUE TITLE
Noto Sans Arabic v2.011: regression with RTL Kerning

### ISSUE THREAD

**Issue by eliheuer** [notofonts/arabic#216]
### Font 
Noto Sans Arabic Regular v2.011

### Where the font came from, and when
QA report from this PR: https://github.com/google/fonts/pull/6859

### Issue
I noticed that some pairs that had RTL kerning before now have less or no RTL kerning, example below.

### Screenshot
Before
<img width="129" alt="Screenshot 2023-11-01 at 10 20 28 AM" src="https://github.com/notofonts/arabic/assets/5162664/ab7bb80e-aca7-432e-a848-d7c05b9611bc">
After
<img width="139" alt="Screenshot 2023-11-01 at 10 20 44 AM" src="https://github.com/notofonts/arabic/assets/5162664/decb843b-5f9c-4f0e-8280-87e72bf0278a">

@khaledhosny This is your call if this is worth fixing, it seems like a regression to me but I could be wrong.

**Comment by simoncozens** [comment]
Feels like a toolchain issue.

**Comment by khaledhosny** [comment]
The kerning was already missing in v2.010, Google Fonts repo seems to have v2.004.

**Comment by khaledhosny** [comment]
There is a +ve kern between @reh and @ain.isol (that is the only RTL kern in the font) and it is been there since the first commit in this repository.

Seems to be #164. I think the old spacing was a little too tight but definitely not a bug. I think I’m going to drop this kern pair.
