### ISSUE TITLE
Noto Sans Arabic v2.011: regression with Arabic number spacing

### ISSUE THREAD

**Issue by eliheuer** [notofonts/arabic#220]
### Font 
Noto Sans Arabic v2.011

### Where the font came from, and when
QA report from this PR: https://github.com/google/fonts/pull/6859

### Issue
Regression with with Arabic number spacing. Note that visually the number spacing has become more irregular since the last update to this font. See example below.

### Screenshot
Before
<img width="217" alt="Screenshot 2023-11-01 at 1 31 19 PM" src="https://github.com/notofonts/arabic/assets/5162664/410ecb0c-c8cd-4114-89c3-863c33065c15">
After
<img width="212" alt="Screenshot 2023-11-01 at 1 31 30 PM" src="https://github.com/notofonts/arabic/assets/5162664/d64de1b0-205d-4aa1-9fad-fcf038230500">

@khaledhosny This is your call if this is worth fixing, it seems like a regression to me but I could be wrong.

**Comment by khaledhosny** [comment]
The numbers are now tabular by default, so the change is intentional and the spacing issue is a side effect of that (because ١ now has more space around it unlike ٩).

There is not much that can be done here, unlike 1, there is not much we can do to make ١ has less white space around it.
