### ISSUE TITLE
Does Noto Sans Arabic support English?

### ISSUE THREAD

**Issue by Barzi-Ahmed** [notofonts/arabic#223]
Hello, I've a question.

I'm making a website that is in Arabic and English, and I use variable font of Noto Sans Arabic, but it seems it doesn't have English characters. I want to use one font not two seperate fonts each for a different language.

What do I do in this situation? Is there a version of Noto Sans Arabic that supports both English and Arabic in one file?

Thank you! 

P.s. 
In any situation, I have to use variable font.

**Comment by simoncozens** [comment]
Hello! You have three options for this situation:

* You can use Google's [hosted version of Noto Sans Arabic](https://fonts.google.com/noto/specimen/Noto+Sans+Arabic) which contains a Latin glyphset:

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@200..900&display=swap" rel="stylesheet">
<style>
body { font-family: 'Noto Sans Arabic', sans-serif; }
</style>
```

* If you want to host the font yourself, you can use *CSS fallback*: you host Noto Sans Arabic *and* Noto Sans, set the font in CSS to be both, (`font-family: Noto Sans Arabic, Noto Sans`) and the user's browser will automatically use Noto Sans Arabic for the Arabic letters and Noto Sans for everything else.
* Or you can host the font yourself and use a "full build" which contains Latin characters. The full builds are available in the "full" directory of the [Noto Sans Arabic release](https://github.com/notofonts/arabic/releases/tag/NotoSansArabic-v2.012).
