### ISSUE TITLE
Allah does not ligate

### ISSUE THREAD

**Issue by curya** [notofonts/arabic#227]
### Title 
Allah does not ligate

### Font 
NotoNaskhArabic[wght].ttf
NotoSansArabic[wdth,wght].ttf
NotoKufiArabic[wght].ttf

### Where the font came from, and when
https://github.com/notofonts/arabic/releases

### Font Version
Naskh 2.018
Sans 2.012
Kufi 2.108

### OS name and version
Windows 10

### Application name and version
All.

### Issue
Allah (الله) does not ligate when typed even though the ligature *does* exist.

  1. Type الله
  2. Observe that it does not change to the ligature.

### Character data
الله

**Comment by Mercury13** [comment]
Well, he did not write character data.
Simple ALLH.
0627+0644+0644+0647

**Comment by curya** [comment]
Probably important to mention that we discussed this issue here: https://github.com/Mercury13/unicodia/issues/324

**Comment by Mercury13** [comment]
Ligate: Amiri (IDK where came from), KacstBook (IDK where came from), Scheherazade New (newest)
Do not ligate: Scheherazade (IDK where came from, replaced with New), Noto Naskh (newest)

**Comment by khaledhosny** [comment]
This is intentional, see https://github.com/notofonts/arabic/issues/192

**Comment by Mercury13** [comment]
#192 says about LLH, I’ll check.
Amiri and KacstBook ligate. Scheherazade New does not. I think, the entire ALLH, should ligate.

**Comment by curya** [comment]
@khaledhosny You said [here](https://github.com/notofonts/arabic/issues/192#issuecomment-1740087564) that الله *should* ligate...

**Comment by khaledhosny** [comment]
> @khaledhosny You said [here](https://github.com/notofonts/arabic/issues/192#issuecomment-1740087564) that الله _should_ ligate...

The sequence there is:
ARABIC LETTER ALEF ا
ARABIC LETTER LAM ل
ARABIC LETTER LAM ل
ARABIC SHADDA ّ
ARABIC LETTER SUPERSCRIPT ALEF ٰ
ARABIC LETTER HEH ه

**Comment by curya** [comment]
It appears that the ligature is not any different from literally typing it out manually. In which case, why even have the ligature at all?

Is there a real world case where you would purposely want to type Allah *without* the shadda and superscript alef?

**Comment by khaledhosny** [comment]
> It appears that the ligature is not any different from literally typing it out manually. In which case, why even have the ligature at all?

That would be a bug.

> Is there a real world case where you would purposely want to type Allah without the shadda and superscript alef?

The sequence might be a different word/part of word in other languages.

**Comment by curya** [comment]
> That would be a bug.
So it is!
![image](https://github.com/notofonts/arabic/assets/71131343/189d662b-a5b5-4fb4-8e97-c3ad579507f7)
Ligatures **on** on the left. Ligatures turned **off** on the right. It seems that this bug only affects Noto Naskh Arabic. It's the only one that doesn't change.
