### ISSUE TITLE
Overlap Issue in Noto Sans Arabic

### ISSUE THREAD

**Issue by curya** [notofonts/arabic#229]
### Font 
NotoSansArabic[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/arabic/releases

### Font Version
2.012

### OS name and version
Windows 10

### Application name and version
Photoshop 2024
Illustrator 2024

### Issue
There appears to be an overlapping issue with certain letters and dots. I only found this one, but there might be more.
It only happens in Noto Sans Arabic. It also only happens in certain weights. As far as I can tell, those are:
ExtraCondensed
ExtraCondensed Medium
Condensed Medium
SemiCondensed Medium
ExtraCondensed SemiBold
Condensed SemiBold
SemiCondensed SemiBold
SemiBold
ExtraCondensed Bold
Condensed Bold
SemiCondensed Bold
Bold
ExtraCondensed ExtraBold
Condensed ExtraBold
ExtraCondensed Black
Condensed Black

Some overlap to a greater extent. Some overlap to a lesser extent.

### Character data
زين

### Screenshot
![image](https://github.com/notofonts/arabic/assets/71131343/984ac10c-5da5-411f-924d-fa65a61604f3)
![image](https://github.com/notofonts/arabic/assets/71131343/77f9bb06-8a9d-4738-b64c-7115d582066c)

**Comment by khaledhosny** [comment]
The tail of the zain touching the dots a little should be OK. The alternatives are probably worse (increasing the spacing which might introduce a visible gap, or moving the dots to the left which would clash with the dots of a following yeh or peh).

**Comment by curya** [comment]
Not an issue at all in the Naskh version:
![image](https://github.com/notofonts/arabic/assets/71131343/49fd8095-52ae-40b8-8518-c28c9d799604)

**Comment by curya** [comment]
Also works just fine in the Black weight:
![image](https://github.com/notofonts/arabic/assets/71131343/e78901f5-0dac-4a43-93d2-daa920faaef7)

**Comment by simoncozens** [comment]
I'm with Khaled on this one; just the construction of this font means that there's no real way to improve it. The Bold and Semibold touches are pretty minimal, and even in the condensed I don't think it affects comprehension at all. Notice that the Naskh has a different rhythm which is why the zain tail ends further out.
