### ISSUE TITLE
Add support for Belarusian Arabic letters

### ISSUE THREAD

**Issue by davelab6** [notofonts/arabic#231]
A user wrote in for Noto Naskh Arabic,

> Please add support for Belarusian Arabic letters:
> 
> U+08AE (arabic letter dal with three dots below) `ࢮ`
> 
> U+08AF (arabic letter sad with three dots below) `ࢯ`

**Comment by simoncozens** [comment]
Good news - these were added last year:

![shape](https://github.com/notofonts/arabic/assets/106728/f4875c17-f2d8-4dd0-a5b3-847b1f5178f0)

**Comment by moyogo** [comment]
Noto Naskh Arabic is still on version 2.016 on Google Fonts. The Unicode 14 characters, including these Belarussian and Polish characters were added in NotoNaskhArabic-v2.017 and the latest version is NotoNaskhArabic-v2.018.

**Comment by simoncozens** [comment]
Huh, that's weird because new Noto releases get automatic google/fonts PRs.

**Comment by simoncozens** [comment]
It was *supposed* to go live in https://github.com/google/fonts/pull/6857.
