### ISSUE TITLE
Incorrect diacritic position for letter jeem when using bullets in InDesign

### ISSUE THREAD

**Issue by robertmiles3** [notofonts/arabic#232]
### Title 
  > Incorrect diacritic position for letter jeem when using bullets in InDesign

### Font 
  > NotoSansArabic/full/variable/NotoSansArabic[wdth,wght].ttf

### Where the font came from, and when
  >   Site: https://github.com/notofonts/arabic/releases/download/NotoSansArabic-v2.012/NotoSansArabic-v2.012.zip
  >   Date: 2024-03-24

### Font Version
  > 2.012

### OS name and version
  > macOS Sonoma 14.4

### Application name and version
  > Adobe InDesign 19.3

### Issue
  > If bullets/numbering is enabled in Adobe InDesign when containing a word with a medial position jeem ج, the dot of the jeem gets out of place. If bullets/numbering are not used, then all is well.

1. Create a text frame using the "ME Type Tool" in InDesign (for a right-to-left text frame).
2. Paste وين نتجمع؟ in the text frame. Notice the dot of the letter jeem is proper, showing below the main part of the letter.
3. Place the caret inside the text frame at the beginning of the phrase.
4. In the "Bullets and Numbering" property section, click the "Numbered List" button to change the line of text to a numbered list.
5. Notice that the dot for the jeem is no longer below the main part of the letter, but rather is now close to the baseline and barely visible.

### Character data
  > وين نتجمع؟

### Screenshot

https://github.com/notofonts/arabic/assets/944302/1c2b36f2-7ba1-4ce9-a5e8-cfec231b3186

**Comment by khaledhosny** [comment]
That is funny. It seems that the bullet list uses a different layout engine than the regular text (most likely InDesign’s pre-HarfBuzz one), and it breaks other things not just the dot of the jeem:
<img width="783" alt="image" src="https://github.com/notofonts/arabic/assets/93914/1cfc1f3e-60d3-4213-b7a3-8201c27cd887">

**Comment by robertmiles3** [comment]
Weird. So is there a solution or a suggestion? Is it fixable on the font side of things or is it strictly an InDesign problem?

**Comment by simoncozens** [comment]
It's an InDesign problem. Nothing to be done for the font.

**Comment by robertmiles3** [comment]
Thanks. I posted a bug report for them, but I'm not holding my breath. Ugh.

**Comment by robertmiles3** [comment]
Reopening this for a minute...any idea why Noto Sans Arabic UI (2.009) functions properly even with the bullets?

<img width="567" alt="image" src="https://github.com/notofonts/arabic/assets/944302/ce12469c-4db9-4f68-b6f9-34140230a41a">

**Comment by simoncozens** [comment]
It uses a different construction - no mark attachment for the nukte.

**Comment by robertmiles3** [comment]
I wouldn’t mind using the UI version except it doesn’t seem to have
parentheses like the regular version does.

**Comment by robertmiles3** [comment]
Is there a way to get Noto Sans Arabic UI "full" version that includes parentheses?

**Comment by simoncozens** [comment]
Yes, it's the same issue. We moved from a "fully composed" model (where for example بت is the two glyphs "beh-ar.init", "tah-ar.fina") to a decomposed model ("behDotless-ar.init", "dotbelow-ar", "behDotless-ar.fina", "twodotsabove-ar") which uses mark attachment to put the dots in the right place. This saves a huge number of glyphs and makes the layout code simpler - but it does rely on applications correctly implementing mark attachment, something which has been part of OpenType since around 2000 but still causes problems for Adobe.

**Comment by robertmiles3** [comment]
Thanks for the response. From the looks of things in the repo, it seems Noto Naskh is also decomposed, right? If so shouldn't that be messed up as well? But it's operating properly. Sorry if these are dumb questions, I'm a font newbie.

**Comment by simoncozens** [comment]
They all use the same engineering. It's possible that you have Noto Naskh as part of your operating system and an older version is being used in preference to the newer one you have installed...

**Comment by khaledhosny** [comment]
https://github.com/notofonts/arabic/pull/247 should fix the _jeem_ dot issue, it does not fix the fact that Adobe’s implementation is buggy or fix other issues I pointed to, but it should be enough to fix the originally reported issue.
