### ISSUE TITLE
Overlap with ح‌ and گ‌

### ISSUE THREAD

**Issue by MAZ06** [notofonts/arabic#234]
### Font 
NotoSansArabic[wdth,wght].ttf - 2.012
NotoKufiArabic[wght].ttf - 2.109

### OS name and version
Windows 10

### Issue
In heavier weights, the ح‌ and گ‌ can overlap in Noto Sans Arabic. Bold is okay, but the problem is obvious in ExtraBold and Black.

The same issue affects Noto Kufi Arabic. The overlap issue is in Regular, Medium, SemiBold, Bold, ExtraBold, and Black.

I noticed this happening in Photoshop. I can easily fix the issue by changing the leading, but I thought I should report it here since the "auto" size defaults to this overlapping problem.

### Character data
فصیح‌
قشنگ‌

### Screenshot
Noto Sans Arabic: Bold, ExtraBold, Black
![image](https://github.com/notofonts/arabic/assets/165231781/77faa8f4-14c3-45a6-b61d-e6e5bfd20efc)

Noto Kufi Arabic: Regular, Medium, SemiBold
![image](https://github.com/notofonts/arabic/assets/165231781/0e5c0414-ba2a-4206-8fe2-7b3cbf3c2f93)

Noto Kufi Arabic: Bold, ExtraBold, Black
![image](https://github.com/notofonts/arabic/assets/165231781/2973bfd8-6819-4b4b-bfb6-351f2d51342b)

**Comment by khaledhosny** [comment]
What application are you using? The line spacing is much tighter that what is set in the font files.

**Comment by khaledhosny** [comment]
I see you mentioned Photoshop above. Photoshop (and other Adobe CC apps) use hard-coded line spacing values and don’t use the values supplied by the font, so there is nothing we can do in the font to fix this.
