### ISSUE TITLE
U+FDFB missing diacritics in Noto Sans Arabic

### ISSUE THREAD

**Issue by MAZ06** [notofonts/arabic#236]
### Font 
NotoSansArabic[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/arabic/releases/tag/NotoSansArabic-v2.012

### Font Version
2.012

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
U+FDFB is missing diacritics in Noto Sans Arabic.

### Character data
ﷻ U+FDFB

### Screenshot
![image](https://github.com/notofonts/arabic/assets/165231781/9686a0de-4f8e-4bfe-9fe2-45ff1fe99107)

**Comment by khaledhosny** [comment]
There are no requirement to have any vowel marks here, it is a design choice.

**Comment by MAZ06** [comment]
I thought that might be the case, but I was confused because Naskh has the diacritics and Sans does not. All the other Sans ligatures have diacritics too...

**Comment by khaledhosny** [comment]
I didn't design either glyph, so I have no authoritative answer to why any of them was designed this way, except what I said earlier.

**Comment by simoncozens** [comment]
Putting this down as a stylistic choice too.
