### ISSUE TITLE
U+FDFA is missing diacritics in Noto Naskh Arabic

### ISSUE THREAD

**Issue by MAZ06** [notofonts/arabic#237]
### Font 
NotoNaskhArabic[wght].ttf

### Where the font came from, and when
https://github.com/notofonts/arabic/releases/tag/NotoNaskhArabic-v2.018

### Font Version
2.018

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
U+FDFA is missing diacritics in Noto Naskh Arabic.

### Character data
ﷺ U+FDFA

### Screenshot
![image](https://github.com/notofonts/arabic/assets/165231781/07e1d28f-92e1-449c-9428-bd2587961e3a)

**Comment by MAZ06** [comment]
﵆ U+FD46 too.
![image](https://github.com/notofonts/arabic/assets/165231781/fac105ec-4a2e-402b-8a90-0f254b867785)

**Comment by simoncozens** [comment]
I'm sure this would be deliberate - @khaledhosny, is this for stylistic reasons?

**Comment by khaledhosny** [comment]
The diacritics are not mandatory, they are added mainly to fill-in the space and give the rectangular formation, otherwise these are common phrases and there is no ambiguity that requires full vocalization.

**Comment by MAZ06** [comment]
I said basically the same thing in my other issue, but all the other ligatures have the same diacritics in both Naskh and Sans. Not sure why this ligature would be any different.

**Comment by MAZ06** [comment]
It's just strange that 99% of the ligatures in Naskh and Sans all have the same diacritics. Why would only the ones I mentioned in these issues not have them? It sounds like a bug/oversight to me. Especially on such important glyphs like ﷺ and ﷻ.

**Comment by khaledhosny** [comment]
There is no bug or oversight here, different designs have different requirements. The glyphs were designed independently and there is no requirements that they match in every minute detail.

**Comment by MAZ06** [comment]
All I can say is that it's strange that 99% of the glyphs follow the same pattern of including all the diacritics. We would have to ask the designer why they chose not to include the diacritics in these important glyphs.

**Comment by simoncozens** [comment]
It's an interesting question, but it's not a bug - just a stylistic choice.
