### ISSUE TITLE
Please Kill Noto Sans Arabic and instead use Naksh for everything.

### ISSUE THREAD

**Issue by Battler624** [notofonts/arabic#239]
This is probably a tall order but the Noto Sans Arabic is very fatiguing to use and hard to read. Noto Naksh on the other hand is the exact opposite, perfect in all regards.

Its only the one font that I would consider over Times New Roman.

**Comment by simoncozens** [comment]
I only provide the fonts, I don't decide who uses them. :-) Is this maybe a question for Android, or do you mean *everyone*? Tall order indeed.

**Comment by MAZ06** [comment]
@Battler624 Do you also hate the Arabic font on [bbc.com](https://www.bbc.com/arabic)? It's very similar to Noto Sans Arabic.
