### ISSUE TITLE
Better joining behavior should be implemented to U+0600 U+0601 U+0604 in All Arabic fonts

### ISSUE THREAD

**Issue by nizarsq** [notofonts/arabic#24]
U+0600 U+0601 U+0604 used in conjunction with digits, digits should sit on the top of those code points. In NotoKufiArabic, NotoSansArabic and NotoNastaliqUrdu no joining occurs . In and NotoNaskhArabic it does join (With exception to U+0604) but it will join any preceding characters which it cause overlap when the preceding are characters too. A better joining behavior should be implemented to all Arabic fonts. I believe specifying the context in which each substitution occurs in calt table will allow to handle those code points correctly.

<img width="1391" alt="Screen Shot 2020-12-29 at 8 32 00 PM" src="https://user-images.githubusercontent.com/22158882/103330108-e95e3a00-4a14-11eb-8aad-8a168df32a50.png">

When characters preceding:
<img width="1392" alt="Screen Shot 2020-12-29 at 8 30 58 PM" src="https://user-images.githubusercontent.com/22158882/103330079-c469c700-4a14-11eb-9d5e-42c024108324.png">

**Comment by simoncozens** [comment]
I'm going to fold this (and the right side bearings issue) into #34.
