### ISSUE TITLE
Rial issue

### ISSUE THREAD

**Issue by MAZ06** [notofonts/arabic#244]
### Font 
NotoKufiArabic[wght].ttf
NotoNaskhArabic[wght].ttf
NotoSansArabic[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/arabic/releases

### Font Version
Noto Kufi Arabic 2.109
Noto Naskh Arabic 2.019
Noto Sans Arabic 2.012

### OS name and version
Windows 11

### Application name and version
Everything I assume, but I first noticed the issue in Adobe products.

### Issue
U+FDFC (﷼) works in Noto Naskh Arabic and Noto Sans Arabic. Noto Kufi Arabic does not provide the symbol itself but instead only the separate letters. I'm not familiar enough with the Kufi style to say if this is intentional or not.

What I found however was that there is no way to select U+FDFC from the Glyphs panel. U+FDFC *is* in there, but clicking it does not result in the actual symbol. In *all* Noto Arabic styles, it reduces to the separate letters. I have to manually type or copy and paste the symbol to get it to show up properly.

Maybe a problem with ligating?

### Character data
﷼ U+FDFC

### Screenshot
Manually copying and pasting U+FDFC:
![image](https://github.com/user-attachments/assets/a88fe05f-3aed-4697-ba48-32bfe88cf1ac)

Selecting U+FDFC from the Glyphs panel:
![image](https://github.com/user-attachments/assets/31546cc4-3f59-46e8-a4e0-94b7019901d3)

**Comment by khaledhosny** [comment]
> U+FDFC (﷼) works in Noto Naskh Arabic and Noto Sans Arabic. Noto Kufi Arabic does not provide the symbol itself but instead only the separate letters. I'm not familiar enough with the Kufi style to say if this is intentional or not.

There is no official special design for the U+FDFC glyph. The Unicode chart simply shows the word ريال. The stylized design in Noto Naskh Arabic is an innovation that Noto Sans Arabic also followed.

> What I found however was that there is no way to select U+FDFC from the Glyphs panel. U+FDFC _is_ in there, but clicking it does not result in the actual symbol. In _all_ Noto Arabic styles, it reduces to the separate letters. I have to manually type or copy and paste the symbol to get it to show up properly.

This looks like an application issue. Have you tried other fonts?

**Comment by MAZ06** [comment]
Personally, I like the stylized design, but you are correct. The Unicode chart doesn't have it. Maybe it should!

It may in fact be an application issue. It seems you're correct again. Multiple Arabic fonts have this same behavior. Very strange...

But I thought I'd report it anyway just in case it was a problem with the font. I'll close the issue now.
