### ISSUE TITLE
 Unexpected Font Style Change in iOS PowerPoint

### ISSUE THREAD

**Issue by umershabib** [notofonts/arabic#249]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 

 Unexpected Font Style Change in iOS PowerPoint

### Font 
Noto Sans
Noto Kufi Arabic

### Where the font came from, and when

  >   Site: https://fonts.google.com/noto/specimen/Noto+Sans
> https://fonts.google.com/noto/specimen/Noto+Kufi+Arabic

### Font Version
Win: Version 2.013

### OS name and version
  > OS ventura 13.6.6.

### Application name and version

Word, Powerpoint, Adobe apps

### Issue

We are writing to report significant rendering issues we are experiencing with the Noto Sans and Noto Kufi Arabic font families in TTF format. 

On iOS devices, when a PowerPoint slide is saved with text formatted in bold using Noto Sans or Noto Kufi Arabic fonts, the font unexpectedly changes to bold italic upon reopening the slide. This behavior is inconsistent and hinders the creation of visually appealing presentations.

We have tried troubleshooting these issues. Unfortunately, these attempts have been unsuccessful in resolving the problems.

We believe these issues are negatively impacting the user experience of our organization and potentially other users of these font families. We kindly request your immediate attention to this matter and a prompt resolution.

**Comment by simoncozens** [comment]
This is not a font issue, as we do not supply italic versions of the Arabic fonts. It must be Powerpoint which is creating the fake italic.

**Comment by umershabib** [comment]
@simoncozens  This issue is with Noto Sans as well not just the arabic version.

**Comment by simoncozens** [comment]
Maybe. But the fact that you are seeing italic Kufi Arabic when the italic font does not exist means it is not a problem with the font.
