### ISSUE TITLE
Redesign Arabic Letter U

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [notofonts/arabic#25]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > The Arabic Letter U (U+06C7) could be designed with a small destinct shape, which features the "filled damma".

### Font 
  > NotoNaskhArabic-Regular.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
  >   Date: 2021-01-02

### OS name and version
  > Windows 10 20H2.

### Issue
In the recent times, both Amiri and Scheherazade New fonts redesigned the Arabic Letter U, making it distinct from the combination of U+0648 U+064F, so Noto Arabic Naskh could follow up anyway.

### Character data
  > https://www.fileformat.info/info/unicode/char/06c7/index.htm

**Comment by simoncozens** [comment]
This is done in bb3c671 in the "naskh-reeng" branch, which will become main after some thorough testing.
