### ISSUE TITLE
Underline feature is mixing in with dots and diacritics

### ISSUE THREAD

**Issue by amoghsrivastava** [notofonts/arabic#250]
### Title 
Underline feature is mixing in with dots and diacritics

### Font 
**NotoSansArabicUI-Regular.ttf** take from the **Full** package

### Where the font came from, and when
Site: https://github.com/notofonts/arabic/releases/download/NotoSansArabicUI-v2.011/NotoSansArabicUI-v2.011.zip
Date: 2024-09-04 (preferred format)

### Font Version
(I used this) Mac - 2.011

### OS name and version
Not pre-installed (User installed)

### Application name and version
Figma, Flutter

### Issue
On using the font on Figma as well as in Flutter framework, the nakat and tashkheel (dots and diacritics) are hitting the underline feature of the font. This is impacting the legibility and clarity of the font when used as a text link with underline. **See screenshot** attached which compares Noto Sans Arabic UI with other standard arabic fonts like "Arial". 

Can we fix this by increasing the underline position a little more? Or guide me on how to do this?

### Character data
I used the text in arabic which translates to 'Order now'. A critical action in our app.

### Screenshot
![image](https://github.com/user-attachments/assets/6b6290aa-3a27-4d22-be5a-3de65ed76859)

### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by simoncozens** [comment]
You should be aware that the UI fonts are deprecated and we do not plan to work on them any more. (They are a compromise which squashes glyphs into Latin vertical metrics; the fix is to use the non-UI fonts and lay out text with script-appropriate metrics instead.)

Of course, this same issues affects the non-UI fonts as well. I'm not sure how Flutter and Figma implement underlining, but some clients don't use the font's `post` table underline position values anyway. The best solution is something like CSS's `text-decoration-skip: ink`; see https://github.com/w3c/alreq/issues/86.

If you want to try editing the font to change the underline position, I recommend using `gftools`; this is available as a Python library:

```
% pip install gftools
% echo 'post->underlinePosition: -200' > fontsetter.config
% gftools-fontsetter -o NotoSansArabicUI-modified.ttf NotoSansArabicUI-Regular.ttf fontsetter.config
```

**Comment by amoghsrivastava** [comment]
Thanks for the reply @simoncozens !

I tried out gftools and it is working so far. I will stress test it with other characters and weights to check how it affects the position. I also saw that you're one of the authors of gftools, which is very cool - only discovering this stuff. 

If I can ask, in your experience, does the `underlinePosition` change anything else in that font or just the height of the underline across that font? 

Another question would be, will using non-UI version of the font instead of UI affect any existing layouts?

**Comment by simoncozens** [comment]
>  does the `underlinePosition` change anything else in that font or just the height of the underline across that font?

Just like the name says, it's the underline position. :-)

> will using non-UI version of the font instead of UI affect any existing layouts?

I am not too sure, but I think the only change in the Arabic font is the vertical metrics. So using the non-UI may increase the size of text boxes.

**Comment by r12a** [comment]
fwiw, a good link to W3C material on this topic can be found at https://www.w3.org/TR/arab-lreq/#text_decoration (this is one of a set of new documents pointing to information by topic). From that link you can find background info, discussions in the alreq repo, discussions in CSS repo, tests, and gap analysis reports. hth
