### ISSUE TITLE
Double Angle Quotation Mark: comic sans vibes

### ISSUE THREAD

**Issue by mustafa0x** [notofonts/arabic#251]
The double angle quotation marks `«»` (U+00AB, U+00BB) are oddly drawn. In contrast to the single angle quotation marks.

<img width="1812" alt="image" src="https://github.com/user-attachments/assets/4e35fc28-be2a-491f-b0fa-27b9556afa42">

https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic?preview.text=«جميل»%20—%20‹عجيب›&query=noto+naskh

**Comment by simoncozens** [comment]
This is because the single quotation marks are not from the same font...

**Comment by mustafa0x** [comment]
Perhaps `«»` can be redesigned to be more aesthetic?

**Comment by khaledhosny** [comment]
`«»` should be rounded in Arabic. I don’t have evidence of `‹›` being (traditionally) used in Arabic, but they should be consistent in design. I think the design of `«»` matches the overall design of Noto Naskh Arabic, though they are usually more like small double parentheses (https://github.com/w3c/alreq/issues/49#issuecomment-222678509):
![](https://cloud.githubusercontent.com/assets/4839211/15674769/7b0e8f6a-2736-11e6-8fc8-23171c90f868.jpg)

**Comment by mustafa0x** [comment]
I strongly agree. My problem is that they seem lopsided. Which is why I said "Comic sans vibes".

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/2956e2bb-8cef-464e-a31b-d94a9d171f64">

**Comment by simoncozens** [comment]
I agree with Khaled that the current design of the double quotes follows the style of Noto Naskh pretty well, and I don't think they feel lopsided. In that situation I don't think a redesign is needed - if you don't agree with the aesthetic decisions of the designer, other fonts are available.

If there's work to do here, it's to make the single quotes consistent. But even then, if the single quotes are not used in Arabic and not actually in this font, why do we need to add them?

**Comment by mustafa0x** [comment]
Thanks @simoncozens, it's definitely a matter of personal preference, so I understand if it won't be accommodated.
