### ISSUE TITLE
Single-letter Kashida

### ISSUE THREAD

**Issue by avidseeker** [notofonts/arabic#253]
Currently, applying Kashida is by adding "ـ" U+0640 ARABIC TATWEEL _between_ letters. However, a more elegant way is by stretching a specific letter within the word. This method is popular with old scriptures, calligraphy, and handwritten messages.

Examples: (Taken from [KFGQPC print](https://books.islamway.net/1/01_Mushaf_AlMadinah_L_549.pdf) of Quran). 

![kaaf-alif-maqsura-kashida](https://github.com/user-attachments/assets/93d1e949-da55-4b1a-9701-eb18a53c50d5)

Single-letter Kashida applied to initial form "كـ" and final "ـى"

![kaaf-baa-kashida](https://github.com/user-attachments/assets/9a8f36c3-7555-4b35-a5a4-9f9da6baf525)

Applied to "ـكـ" and "ـب" in  "الكتب"

![kaaf-faa-kashida](https://github.com/user-attachments/assets/ac1b8e45-0091-4aaa-ab30-0fc7183e57d6)

Applied to "كـ" and "ـف" in "كيف"

![kaf-kashida](https://github.com/user-attachments/assets/97360c51-15a6-403f-974d-0c6ba51e7876)

Applied to "ـكـ"

![regular-kashida](https://github.com/user-attachments/assets/d2831103-02b3-4734-9562-84614c425daa)

Applied to last two connected letters in "الناس" (notice that س and ا are not connected) and last two connected letters in "عظيم".

**Comment by simoncozens** [comment]
This is true, and there are proposals to add this to OpenType fonts using a variation axis. However, there are practical difficulties; the rules for applying kashida variation are quite involved - you typically don't want to apply stretching to all glyphs in a word. Therefore you need to set different glyphs at different positions on the variation axis. But changing the variations creates a new run of text; this breaks shaping because the shaper applies initial/medial/final orthographic features do each run separately. So it's not something we can easily do at the moment, and that's why it's out of scope for Noto at this time.

**Comment by avidseeker** [comment]
I wrote an rough algorithm here: https://github.com/latex3/babel/issues/317

> Here is a rough estimate of the algorithm for the improved Kashida. 
> - Start with the last word in a line, and apply stretching to the final letter in that word.
> - However, if the letter is not "stretch-able" (e.g: Arabic Meem م), then look for middle-form Kaaf (ك) and stretch that
> - If there is no Kaaf, apply the fallback Kashida by adding TATWEEL between letters.
> - TATWEEL is usually added to the last two connected letters. These letters are not necessarily the last letters of the word since they could be in isolated form (e.g: "الماء" --> "المـــاء") Notice that "اء" are isolated (they cannot connect).
> - Stretch-able letter forms are: كـ, ـن, ن, ت, ـت, س, ـس, ص, ـص, ـى, ى, ف, ـف (where س and ت also their dotted variants e.g: ش and ث). Also have a look on https://en.wikipedia.org/wiki/Arabic_alphabet#Table_of_basic_letters for reference.

I didn't include it because I thought the algorithm implementation is out-of-scope for a font. A font provides glyphs, and leaves implementation to backend (e.g: latex, libreoffice, etc.).

> add this to OpenType fonts using a variation axis

Why can't this be a start? instead of getting overwhelmed with implementation details that can be left for later...

**Comment by simoncozens** [comment]
Noto is an open source project, so of course I cannot stop you from adding it to a fork. But it's unlikely to happen here until a) the implementation challenges are overcome, and b) there's sufficient need for this to justify adding the additional axis to every Android device in the world.
