### ISSUE TITLE
Extended Arabic-Indic Digit Seven "۷" of Noto Naskh Arabic family is broken

### ISSUE THREAD

**Issue by ebraminio** [notofonts/arabic#27]
Just to note this is a recent regression apparently and can be considered a high priority for Persian, saw it in my Linux desktop but hopefully it won't make its way into Android or any other place,

Steps to reproduce:
1. https://github.com/googlefonts/noto-fonts/blob/99d0402/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf?raw=true
    (the current version)
2. Print this character somehow "۷", maybe in Linux using hb-view,
    "hb-view NotoNaskhArabic-Regular.ttf ۷"

Actual:
![image](https://user-images.githubusercontent.com/833473/117323565-4034be00-aea4-11eb-8492-445187dd7a6f.png)

Apparently Urdu specific shape of digit 7 has replaced the default one every other fonts uses,

Expected:
Just like the current result of Noto Kufi for example,
![image](https://user-images.githubusercontent.com/833473/117324258-e08ae280-aea4-11eb-8293-400a6455bfee.png)

7 should be shown with a V like shape for the character "۷"

Every other font is like:

![image](https://user-images.githubusercontent.com/833473/117326363-d36ef300-aea6-11eb-956c-cf7f20cb958e.png)

But Noto Naskh has become like this

![image](https://user-images.githubusercontent.com/833473/117326461-e97cb380-aea6-11eb-8b18-3c5f15bee924.png)

**Comment by chrissimpkins** [comment]
Possibly related https://github.com/flutter/flutter/issues/108165

**Comment by ebraminio** [comment]
After years I download the latest version of Noto from https://github.com/notofonts/arabic/releases/download/NotoNaskhArabic-v2.019/NotoNaskhArabic-v2.019.zip and this was indeed fixed

![image](https://github.com/notofonts/arabic/assets/833473/ea678837-f1d8-44f2-be86-85403c9086cd)

And thanks!

But somehow a just installed installation of Ubuntu 24.04 has the defected version which apparently has this version of the package, `fonts-noto-core/noble,noble,now 20201225-2`,

data:text/html;charset=utf8,<div style="font-family: 'Noto Naskh Arabic'; font-size: 60">%DB%B4%DB%B7</div>

![image](https://github.com/notofonts/arabic/assets/833473/b77044ea-f8de-4b1d-b46f-11d909c2442f)

So guess I should somehow contact Canonical (or Debian?) for this.
