### ISSUE TITLE
NotoSansArabic-GX and NotoSansArabicUI-GX clip diacritics

### ISSUE THREAD

**Issue by nizarsq** [notofonts/arabic#3]
Clipped diacritics noticed when NotoSansArabic-GX and NotoSansArabicUI-GX used, diacritics placed on either the top or the bottom of some characters (high- end and low-end boundaries characters) those diacritics will either partially clipped or fully clipped (disappeared). Tested  this string "بليغٍ مسلمةٌ" on Android, FontView and Keep App and the results showing as the following:
1-FontView, diacritics on the top show clipping on the bottom appear to be fine.
2-Keep, shows clipping for both top and the bottom diacritics.
3-Personal tool, shows clipping for both top and the bottom diacritics.

Please check attached screenshots
![screen shot 2017-02-16 at 10 25 32 am](https://cloud.githubusercontent.com/assets/22158882/23035265/60a49032-f433-11e6-92c8-39b02b4eee46.png)

![keep](https://cloud.githubusercontent.com/assets/22158882/23035146/0a63d2aa-f433-11e6-9805-f9e7805584bb.png)

![screenshot_ -](https://cloud.githubusercontent.com/assets/22158882/23035153/0d3666dc-f433-11e6-9801-53b6f05648fb.png)

**Comment by simoncozens** [comment]
I think to be honest we're not going to do anything special about this; we're going to use the GF approach to vertical metrics, and users who need bigger linespacing can extend the linespace in their applications. There's a difference between clipping and going outside the box, and I don't think we're actually seeing clipping here.
