### ISSUE TITLE
Incorrect orientation of dots in Noto Sans Arabic

### ISSUE THREAD

**Issue by Etewilak** [notofonts/arabic#33]
The dots of U+08AE and U+08AF in Noto Sans Arabic are oriented incorrectly.
The following shows the issue:
![image](https://user-images.githubusercontent.com/55674356/153587688-314c34c6-418f-4002-895f-beda943b76cc.png)

**Comment by mskf1383** [comment]
I have the same problem

**Comment by mskf1383** [comment]
I don't have this problem with the latest version

**Comment by hedayat** [comment]
> It also includes both forms (connected and separated) of "پ" (It seems that it is U+067E).
> 
> ![image](https://user-images.githubusercontent.com/497092/164977029-40644c3a-63a6-49b3-8629-fed102ab5f9e.png)
> 
> I just found issue #31, and it seems that the glyph used for U+0752 should be used for U+067E and vice versa!


This is fixed for me too.

**Comment by khaledhosny** [comment]
This is fixed now.
