### ISSUE TITLE
Noto Sans Arabic Font

### ISSUE THREAD

**Issue by khabatPro** [notofonts/arabic#35]
Hi, I want to use Noto Sans Arabic font but it has a problem with letter "ڕ" when links to another letter like "بڕ" or "سڕ" or "تڕ", its shape is changed to irregular shape which is not a standard shape. I need help. 

Regards

![ZE0x4WIDnhHDIGNf.png](https://user-images.githubusercontent.com/71611094/173248050-0cdd574f-5f0a-44ba-940a-07d109de43d1.png)

**Comment by simoncozens** [comment]
Just an update on this: we could not get the new version of Noto Sans Arabic added to Google Fonts as we found some design regressions that we need to work through. I am working on new versions of all the Arabic fonts and am hoping to get them onboarded to Google Fonts soon, but unfortunately I don't have a timeframe.

**Comment by simoncozens** [comment]
Thanks to @khaledhosny 's work, we will release a new Sans Arabic this quarter, and it will hit Google Fonts either end of this quarter or end of next quarter.
