### ISSUE TITLE
Noto Sans Arabic: missing latin characters 

### ISSUE THREAD

**Issue by shacharoz** [notofonts/arabic#37]
## Defect Report
> Noto fonts can be obtained from https://github.com/googlefonts/noto-fonts/tree/master/unhinted/otf/ (unhinted OTF) or https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/ (hinted TTF). If you find a problem with either of these then please use this template to file a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
missing latin characters inside the arabic font

### Font 
NotoSansArabic-VariableFont_wdth,wght.ttf

### Where the font came from, and when
https://fonts.google.com/noto/specimen/Noto+Sans+Arabic
date 23.5.2022

### Font Version
 Win 

### Issue
  inside font package, there are arabic letters. but latin letters are empty. when using the font in an app, a single text field can receive only one font. therefore i cannot write text in both arabic and latin characters at the same time.
this issue DOES NOT exist for all other font files (such as chinese, japanese, russian, greek and korean).

![image](https://user-images.githubusercontent.com/593642/169836467-83342517-9208-420b-a000-9b9438ce8d0f.png)

**Comment by simoncozens** [comment]
We will update Google Fonts with a version containing Latin letters.

**Comment by GustavPS** [comment]
I'm still seeing this issue from google font, have it been updated yet?

**Comment by simoncozens** [comment]
We have not yet updated Noto Sans Arabic on Google Fonts, as we need to understand some of the design changes. If you need a version with Latin glyphs for offline use, you can use the "full" versions in the release [here](https://github.com/notofonts/arabic/releases/tag/NotoSansArabic-v2.010)

**Comment by GustavPS** [comment]
Thanks, looks lite it have the same license as the one on google-font, is that correct? If so then yes I can use that one instead

**Comment by simoncozens** [comment]
Yes, same license. Enjoy!

**Comment by shacharoz** [comment]
Thank you !

Can you give me a timeline for this update?

**Comment by Chrisp90** [comment]
Hi @simoncozens, I have been testing the temp version you pointed to, and it works well for most of the font typefaces, but Latin characters as well as a lot of symbols (punctuations, mathematical signs, etc.) are not supported for Light and Bold. In addition, the +/- glyph is not supported in any typeface of the Noto Sans Arabic. I have screenshots to share if needed. Is this supposed to be part of the upcoming update?
