### ISSUE TITLE
Noto Kufi Arabic doesn't render in Powerpoint on Windows

### ISSUE THREAD

**Issue by michaelmee** [notofonts/arabic#4]
## Noto Kufi Arabic doesn't render in Powerpoint on Windows. 

After installing Onto Kufi Arabic, restarting Powerpoint and entering text with Noto Kufi Arabic selected, a default font appears instead of the expected font. 

It does, however work as expected in:

- Word on Windows
- Powerpoint on Mac OS. 

Office 365: version 16.0.8067.2115
OS: Windows 10 Enterprise

Font: NotoKufiArabic-Regular.ttf
From: https://raw.githubusercontent.com/googlei18n/noto-fonts/master/hinted/NotoKufiArabic-Regular.ttf
Date: 2017-05-30
Version: 1.04

![noto kufi arabic](https://cloud.githubusercontent.com/assets/14109122/26731772/644b513c-47b5-11e7-9923-37dca743470e.png)

**Comment by simoncozens** [comment]
I've had no feedback on this for a year, and I don't have access to Powerpoint to test. If anyone can test the new version and finds a problem, I'll reopen.

**Comment by mdqara** [comment]
Thanks, give me a day and I’ll get back to you

**Comment by mdqara** [comment]
Hello @simoncozens 
I can confirm the problem still exist exactly like what is shown on this: https://github.com/notofonts/arabic/issues/4#issuecomment-1160638549

My powerpoint version is: 2303 (build: 16227.20318)

**Comment by mdqara** [comment]
> Thanks, Chris! @mdqara, please try Chris’ linked file. (I would test it myself but don’t have a Windows computer or PowerPoint…)

I have tested out Chris linked file but the same problem as well
