### ISSUE TITLE
Noto Sans Arabic needs GSUB for Sindhi digit shapes

### ISSUE THREAD

**Issue by roozbehp** [notofonts/arabic#5]
Sindhi digits shapes are different from the Persian and Urdu digits shapes. So Noto Sans Arabic needs a separate GSUB lookup for Sindhi digits. The information in Noto Naskh Arabic is correct for Sindhi, so it could be copied to Noto Sans Arabic. (See also https://github.com/googlei18n/noto-fonts/issues/975.)

**Comment by simoncozens** [comment]
Here's Naskh (correct):

۴۶۷ (language=fa)
![shape](https://user-images.githubusercontent.com/106728/213996365-56f7fa33-e286-4759-bab6-4d14917f98a4.png)
(language=urd)
![shape](https://user-images.githubusercontent.com/106728/213996490-af86eaaa-d559-4129-bc4a-4e41f9d4b9f1.png)
(language=snd)
![shape](https://user-images.githubusercontent.com/106728/213996536-572df989-19d1-4380-b4b9-250e9f08b1ee.png)

In Sans, the six and seven in Sindhi are wrong:
![shape](https://user-images.githubusercontent.com/106728/213996691-9c9808f1-8a46-4902-a2ee-a43cad94f339.png)
