### ISSUE TITLE
Arabic subtending marks doesn’t work under Arabic-Indic digits

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [notofonts/arabic#6]
### Font 
NotoNaskhArabic-Regular.ttf
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
* Noto Naskh Arabic
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNaskhArabic-hinted.zip
Date: 2018-01-10
* Noto Nastaliq Urdu
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip
Date: 2016-10-27

### Font Version
Noto Naskh Arabic: 1.07
Noto Nastaliq Urdu: 1.02 uh

### OS name and version
Windows 10 v1709

### Application name and version
LibreOffice 6.0.0.1 (This is already bundled Noto Naskh Arabic 1.06, but I replacing the Naskh font by newer version after installation)

### Issue
If I insert Arabic subtending marks (U+0604, U+0601), they should placing a horizontal stroke under numbers. However is doesn’t appear with Noto Naskh Arabic and Noto Nastaliq Urdu, even if I insert RLO and PDF characters surrounding them as an instruction mentioned in [this page](http://software.sil.org/awami/features-demo/). The usage of these subtending marks have documented in [N3734](https://www.unicode.org/L2/L2009/09144r3-arabic-samvat.pdf).

### Screenshot
![1](https://i.imgur.com/XDcwkrk.png)

**Comment by simoncozens** [comment]
I'm gathering all the subtending marks issues under #34.
