### ISSUE TITLE
Broken Arabic lam-alef combinations

### ISSUE THREAD

**Issue by khaledhosny** [notofonts/arabic#8]
### Font 
`NotoSansArabic-Regular.otf` and possibly other Noto Sans Arabic fonts.

### Where the font came from, and when
From git master branch.

### Issue
Many Arabic lam-alef combinations are either not ligated or not connected at all. They should all be ligated just like `لا`.

### Character data
ڵآ ڶآ ڷآ ڸآ ݪآ ࢦآ ڵأ ڶأ ڷأ ڸأ ݪأ ࢦأ ڵإ
ڶإ ڷإ ڸإ ݪإ ࢦإ ڵا ڶا ڷا ڸا ݪا ࢦا ڵٱ ڶٱ
ڷٱ ڸٱ ݪٱ ࢦٱ لٲ ڵٲ ڶٲ ڷٲ ڸٲ ݪٲ ࢦٲ لٳ ڵٳ
ڶٳ ڷٳ ڸٳ ݪٳ ࢦٳ لٵ ڵٵ ڶٵ ڷٵ ڸٵ ݪٵ ࢦٵ لݳ
ڵݳ ڶݳ ڷݳ ڸݳ ݪݳ ࢦݳ لݴ ڵݴ ڶݴ ڷݴ ڸݴ ݪݴ ࢦݴ

### Screenshot
![screenshot](https://user-images.githubusercontent.com/93914/37565307-abbf3abe-2aaf-11e8-95ef-7f64b3206bda.png)

They should all look like (with different dots etc. of course):
![la](https://user-images.githubusercontent.com/93914/37565320-e3946428-2aaf-11e8-8499-bee5c38734c4.png)

**Comment by mintty** [comment]
Trying to implement this for a terminal, just asking for some expertise or reference:
In the matrix above, what about some missing ones:
LAM WITH SMALL ARABIC LETTER TAH ABOVE
ALEF WITH DOT ABOVE
ALEF WITH ATTACHED FATHA/KASRA/...
